# Generated by Django 4.0 on 2022-03-27 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='idUserFK',
        ),
    ]
